# Generated by Django 2.1.7 on 2019-03-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_type', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_synopsis', models.TextField()),
                ('book_image', models.CharField(max_length=255)),
                ('update_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('this_book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookName')),
            ],
        ),
    ]
