# Generated by Django 2.1.7 on 2019-03-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='content',
            new_name='section_content',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='section_tables',
        ),
    ]
